apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shoreline.fullname" . }}
  labels:
{{ include "shoreline.labels" . | indent 4 }}
type: Opaque
data:
  GEOSERVER_PASSWORD: {{ .Values.geoserver.admin.password | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
  POSTGRES_USER: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  SECRET_KEY_BASE: {{ randAlphaNum 20 | b64enc | quote }}
  {{- if eq "smtp" .Values.shoreline.email.delivery_method }}
  SMTP_PASSWORD: {{ .Values.shoreline.email.smtp_settings.password }}
  {{- end }}
